version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: bulletify_querier
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: bulletify_querier
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
